import React from "react"
// FaBurn
import {Card,Button} from "react-bootstrap"
// FaInfo
import { FaInfo } from 'react-icons/fa'
const Features = () => {
    return(
        <div className = " bg-dark text-white text-center " id = "features">
            <div className = "row p-4">
                <div className = "col-lg-8">
                    <div className = "row">
                        <div className = "col-lg-6 px-5">
                            <Card style={{ width: '18rem' }} className = "text-dark ">
                                <Card.Img variant="top" src="https://static.thenounproject.com/png/153802-200.png"/>
                                <Card.Body>
                                <Card.Title>Carbon Footprint</Card.Title>
                                <Card.Text>
                                A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
                                </Card.Text>
                                <a className="btn btn-primary btn-outline-light btn-social mx-1" href = "#feature1"><FaInfo/></a>
                                </Card.Body>
                            </Card>
                        </div>
                        <div className = "col-lg-6 px-5">
                            <Card style={{ width: '18rem' }} className = "text-dark ">
                                <Card.Img variant="top" src="https://richmondvale.org/images/easyblog_images/115/b2ap3_large_540219990-300x300.jpg"/>
                                <Card.Body>
                                <Card.Title>Reduce Carbon Footprint</Card.Title>
                                <Card.Text>
                                Reduce Your Carbon Footprint From Driving · Alternatives to drivingWhen possible, walk or ride your bike in order to avoid carbon emissions completely
                                </Card.Text>
                                <a className="btn btn-primary btn-outline-light btn-social mx-1" href = "#feature2"><FaInfo/></a>
                                </Card.Body>
                            </Card>
                        </div>
                    </div>
                    
                </div>
                <div className = "col-lg-4">
                    <h4>Calculate your carbon footprint</h4>
                    <Button className = "m-3" href = "/CarbonCalculator">Click!</Button>
                </div>
            </div>
        </div>
    )
}

export default Features