import React from "react"

const ReduceCarbonFootprintInfo = () => {
    return(
        <div className = "bg-white text-center text-dark p-5" id="feature2">
            <h4>Reduce your carbon footprint</h4>
            <p className = "font-weight-normal">A carbon footprint is the total amount of greenhouse gases 
            (including carbon dioxide and methane) that are generated by our actions.
            The average carbon footprint for a person in the United States is 16 tons, 
            one of the highest rates in the world. Globally, the average is closer to 4 tons.
             To have the best chance of avoiding a 2℃ rise in global temperatures, 
             the average global carbon footprint per year needs to drop under 2 tons by 2050.
            Lowering individual carbon footprints from 16 tons to 2 tons doesn’t happen overnight! 
            By making small changes to our actions, like eating less meat, taking less connecting
             flights and line drying our clothes, we can start making a big difference.</p>
             <img src = "https://richmondvale.org/images/easyblog_images/115/b2ap3_large_540219990-300x300.jpg" className = "img-fluid"></img>
        </div>
        
        
    )
}


export default ReduceCarbonFootprintInfo